"""Generate src/components/filters/countries.ts from country-converter.

Run from this directory with:

    uvx --from country-converter python generate_countries.py

The script has no project dependencies — country-converter is fetched
on demand by uvx. Re-run whenever the upstream country list shifts.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import country_converter as coco

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "components" / "filters" / "countries.ts"

# country-converter stores ISO2 as a regex alternation for codes with
# legacy aliases (e.g. "^GR$|^EL$" for Greece). Take the first 2-letter
# token — that's the canonical ISO 3166-1 alpha-2.
ISO2_RE = re.compile(r"([A-Z]{2})")


def canonical_iso2(raw: str) -> str:
    match = ISO2_RE.search(raw)
    if match is None:
        raise ValueError(f"no ISO 3166-1 alpha-2 code in {raw!r}")
    return match.group(1)


def main() -> None:
    cc = coco.CountryConverter()
    rows = [
        {"code": canonical_iso2(r.ISO2), "name": r.name_short}
        for r in cc.data.itertuples(index=False)
    ]
    rows.sort(key=lambda r: r["name"])

    body = ",\n".join(
        f"  {{ code: {json.dumps(r['code'])}, name: {json.dumps(r['name'], ensure_ascii=False)} }}"
        for r in rows
    )
    contents = (
        "// Generated by scripts/generate_countries.py via country-converter.\n"
        "// Do not edit by hand — re-run the script to refresh.\n"
        "\n"
        "export interface Country {\n"
        "  readonly code: string;\n"
        "  readonly name: string;\n"
        "}\n"
        "\n"
        "export const COUNTRIES: ReadonlyArray<Country> = [\n"
        f"{body},\n"
        "];\n"
    )
    OUTPUT.write_text(contents, encoding="utf-8")
    print(f"wrote {len(rows)} countries to {OUTPUT}")


if __name__ == "__main__":
    main()
